service: dipppp84-import-service
useDotenv: true

provider:
  name: aws
  runtime: nodejs16.x
  region: eu-west-1
  environment:
    BUCKET_NAME: ${env:BUCKET_NAME}
  iam:
    role:
      statements:
        - Effect: Allow
          Action: s3:ListBucket
          Resource:
            - arn:aws:s3:::${env:BUCKET_NAME}
        - Effect: Allow
          Action:
            - s3:*
          Resource:
            - arn:aws:s3:::${env:BUCKET_NAME}/*

plugins:
  - serverless-webpack

functions:
  importProductsFile:
    handler: src/handler.importProductsFile
    events:
      - http:
          method: get
          path: /import
          cors: true
          request:
            parameters:
              querystrings:
                name: true
  importFileParser:
    handler: src/handler.importFileParser
    events:
      - s3:
          bucket: ${env:BUCKET_NAME}
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploaded/
          existing: true